name: petday
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.0
  flutter_svg: ^2.2.3   # ðŸ‘ˆ IMPORTANTE para SVG
  image_picker: ^1.0.7
  image_picker_for_web: ^3.0.4
  firebase_storage: ^11.6.5

  # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.0
  firebase_analytics: ^10.8.0
  cloud_functions: ^4.7.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/google/
    
